openapi: 3.1.0
info:
  title: VOSI endpoints
  version: "1.2"
  description: This is an example of using VOSI-1.2 components.
servers:
- url: /example
paths:
# notes: this is how another service like TAP would include VOSI endpoints using 
# a local copy; the commented out $ref to a standard location would also work
    /tables:
        $ref: ./vosi-tableset.yaml
        #$ref: https://ivoa.net/std/VOSI/vosi-tableset.yaml
    /tables/{name}:
        $ref: ./vosi-table.yaml
        #$ref: https://ivoa.net/std/VOSI/vosi-table.yaml
    /capabilities:
        $ref: ./paths/vosi-capabilities.yaml
        #$ref: https://ivoa.net/std/VOSI/vosi-capabilities.yaml
