openapi: 3.1.0
info:
  title: VOSI endpoints
  version: "1.2"
  description: This is an example of using VOSI-1.2 components.
servers:
- url: /example

tags:
    - name: VOSI Capabilities
    - name: VOSI Table Metadata
    - name: VOSI Table Operations

paths:
# notes: this is how another service like TAP would include VOSI endpoints using 
# a local copy; the commented out $ref to a standard location would also work
    /tables:
        $ref: ./openapi/vosi/vosi-tableset.yaml
        #$ref: https://ivoa.net/std/VOSI/vosi-tableset.yaml
    /tables/{name}:
        $ref: ./openapi/vosi/vosi-table.yaml
        #$ref: https://ivoa.net/std/VOSI/vosi-table.yaml

    /capabilities:
        $ref: ./openapi/vosi/vosi-capabilities.yaml
        #$ref: https://ivoa.net/std/VOSI/vosi-capabilities.yaml

    /table-ops:
        $ref: ./openapi/vosi/vosi-table-ops.yaml
    /table-ops/{jobID}:
        $ref: ./openapi/vosi/vosi-table-ops-job.yaml
    /table-ops/{jobID}/phase:
        $ref: ./openapi/vosi/vosi-table-ops-job-phase.yaml
